/**
 * Appends supplemental educational questions to generate-banks output.
 * Run: node scripts/generate-banks.mjs && node scripts/expand-to-750.mjs
 */
import fs from "fs";
import path from "path";

const outDir = path.join(process.cwd(), "src/data/questions");

function parseQuestions(file) {
  const src = fs.readFileSync(path.join(outDir, file), "utf8");
  const items = [];
  const re =
    /\{\s*id:\s*"([^"]+)",\s*domain:\s*"([^"]+)",\s*prompt:\s*"((?:\\.|[^"\\])*)",\s*choices:\s*(\[[^\]]*\]),\s*correctIndex:\s*(\d+),\s*explanation:\s*"((?:\\.|[^"\\])*)"\s*,?\s*\}/g;
  let m;
  while ((m = re.exec(src))) {
    items.push({
      id: m[1],
      domain: m[2],
      prompt: m[3],
      choices: JSON.parse(m[4]),
      correctIndex: Number(m[5]),
      explanation: m[6],
    });
  }
  return items;
}

function writeDomain(file, exportName, questions) {
  const body = questions
    .map(
      (q) => `  {
    id: ${JSON.stringify(q.id)},
    domain: ${JSON.stringify(q.domain)},
    prompt: ${JSON.stringify(q.prompt)},
    choices: ${JSON.stringify(q.choices)},
    correctIndex: ${q.correctIndex},
    explanation: ${JSON.stringify(q.explanation)},
  }`,
    )
    .join(",\n");
  fs.writeFileSync(
    path.join(outDir, file),
    `import type { Question } from "../types";

/** Original educational practice items. Not real Pearson VUE / TDI exam questions. */
export const ${exportName}: Question[] = [
${body},
];
`,
  );
}

function mc(domain, prefix, n, prompt, correct, wrongs, explanation) {
  const choices = [correct, ...wrongs].slice(0, 4);
  const rot = n % 4;
  const rotated = [...choices.slice(rot), ...choices.slice(0, rot)];
  return {
    id: `${prefix}-${String(n).padStart(3, "0")}`,
    domain,
    prompt,
    choices: rotated,
    correctIndex: rotated.indexOf(correct),
    explanation,
  };
}

const TARGETS = {
  life: 150,
  health: 150,
  annuity: 120,
  ethics: 120,
  "texas-law": 150,
};

const SUPPLEMENT = {
  life: [
    ["Which provision lets a policyowner inspect the contract shortly after delivery?", "Free-look / right to examine", ["Mandatory 90-day waiting period", "Automatic license renewal", "Guaranty association payout"], "Free-look protects buyers with a short cancellation window."],
    ["What does the incontestability clause generally limit after a period?", "Late challenges based on application misrepresentation", ["All future premium increases", "Beneficiary changes forever", "State exam retakes"], "Incontestability narrows insurer contest rights after time passes."],
    ["A policy loan against cash value typically:", "Reduces net death benefit if unpaid at death", ["Doubles the face amount", "Eliminates underwriting", "Creates Medicare eligibility"], "Outstanding loans offset proceeds."],
    ["The purpose of a suicide clause is usually to:", "Limit early suicide claims and may return premiums", ["Pay double indemnity always", "Waive all future premiums", "Convert term to whole life"], "Early suicide limits protect against anti-selection."],
    ["Paid-up additions use dividends to:", "Buy small amounts of additional permanent insurance", ["Pay state licensing fees", "Fund auto liability", "Replace CE hours"], "PUAs grow permanent coverage."],
    ["A waiver of premium rider generally waives premiums when:", "The insured becomes totally disabled as defined", ["The agent misses CE", "Stock markets fall", "The beneficiary changes"], "WOP triggers on qualifying disability."],
    ["Extended term nonforfeiture uses cash value to:", "Purchase term insurance for a limited period", ["Buy flood coverage", "Pay Pearson VUE fees", "Fund annuities only"], "Extended term continues temporary protection."],
    ["Reduced paid-up nonforfeiture gives the owner:", "A smaller permanent face amount with no further premiums", ["Unlimited free coverage", "Only AD&D", "Medicare Part D"], "RPU preserves some permanent protection."],
    ["Variable life policies expose the owner to:", "Investment risk in separate account subaccounts", ["Zero market risk always", "Only Texas law penalties", "Workers comp exclusive remedy"], "Variable cash values fluctuate with investments."],
    ["Universal life differs from traditional whole life mainly by:", "Flexible premiums and adjustable death benefits within rules", ["Having no death benefit", "Being identical to term ART", "Requiring no application"], "UL emphasizes flexibility."],
    ["A key person life policy is bought by a business to:", "Offset financial loss if a critical employee dies", ["Insure the building roof", "Pay CE fines", "Replace Medicaid"], "Key person coverage protects firm value."],
    ["Credit life insurance is designed to:", "Pay off a loan balance if the debtor dies", ["Insure pets", "Cover homeowners flood", "Fund 401(k) loans"], "Credit life protects lenders/borrowers on loans."],
    ["The face amount of a policy generally means:", "The base stated death benefit before certain adjustments", ["Monthly modal fee only", "Agent override", "CE certificate"], "Face amount is the nominal death benefit."],
    ["A contingent beneficiary receives proceeds when:", "The primary beneficiary cannot take them", ["Always before the primary", "Only on annuities", "Never in Texas"], "Contingent is the backup line."],
    ["Per stirpes beneficiary language generally means:", "A deceased beneficiary's share passes to their descendants", ["Everything goes to the insurer", "Only charities receive", "Proceeds are forfeited"], "Per stirpes preserves lineage shares."],
    ["An absolute assignment transfers:", "Ownership rights in the policy", ["Only the agent's commission", "Only CE records", "Only auto PIP"], "Absolute assignment changes ownership."],
    ["Collateral assignment is commonly used to:", "Secure a loan with the policy as collateral", ["Delete all beneficiaries", "Avoid free-look", "Create STOLI"], "Lenders take collateral interests."],
    ["A rated substandard policy usually means:", "Extra premium for higher assessed risk", ["Free coverage forever", "Automatic decline", "No death benefit"], "Ratings load premium for risk."],
    ["Guaranteed insurability options allow:", "Buying additional coverage at future dates without new medical evidence, within limits", ["Skipping all premiums", "Unlimited tax-free income", "Avoiding appointments"], "GIR preserves insurability windows."],
    ["Accelerated death benefits may allow:", "Early access to part of the death benefit for qualifying conditions", ["Free auto collision", "Medicare enrollment", "License printing"], "ADB advances proceeds under triggers."],
    ["A life settlement involves:", "Selling an existing policy to a third party for cash", ["Buying term only online", "Getting CE credit", "Filing workers comp"], "Settlements transfer ownership for payment."],
    ["MEC status on a life contract mainly affects:", "Taxation of distributions during lifetime", ["Auto liability minimums", "Flood zones", "CDL endorsements"], "MEC rules change tax treatment."],
    ["Human life value methods estimate:", "Economic value of future earnings for needs analysis", ["Only funeral costs", "Stock betas", "Mileage reimbursement"], "HLV quantifies income replacement."],
    ["Needs analysis for life insurance typically includes:", "Final expenses, income replacement, debts, and education", ["Only social media metrics", "Favorite hobbies", "DMV points"], "Needs analysis matches coverage to obligations."],
    ["A conditional receipt may create:", "Temporary coverage subject to stated conditions after application/premium", ["Permanent free insurance", "Automatic appointments", "Guaranty sales pitches"], "Receipts can start interim coverage."],
    ["Joint first-to-die life insurance pays when:", "The first of the insured persons dies", ["Both must die", "Only at age 100", "Never"], "First-to-die pays on first death."],
    ["Survivorship second-to-die life pays when:", "The second insured dies", ["The first sneeze", "Monthly while living", "Only for AD&D"], "Survivorship is estate-planning oriented."],
    ["Annual renewable term premiums typically:", "Increase as the insured ages at renewal", ["Stay level for 30 years always", "Build cash value like whole life", "Are illegal"], "ART steps up with age."],
    ["Decreasing term is often used to cover:", "A shrinking obligation such as a mortgage balance", ["Growing cash value", "Unlimited UL", "Annuitization only"], "Decreasing term matches declining debt."],
    ["A spendthrift settlement option can help:", "Protect installment proceeds from beneficiary creditors under rules", ["Increase agent commissions", "Skip underwriting", "End CE"], "Spendthrift clauses protect installment payouts."],
    ["Interest-only settlement options pay:", "Interest on retained proceeds while principal stays with insurer under rules", ["The entire face weekly forever", "Only dividends", "Medicare Part B"], "Interest-only holds principal at insurer."],
    ["Fixed-period settlement options pay:", "Installments over a chosen number of years", ["Only one share of stock", "Agent residuals", "Title fees"], "Fixed-period annuitizes proceeds over time."],
    ["Life income settlement options resemble:", "Annuitizing proceeds for lifetime payments", ["Term renewals only", "Auto liability", "Flood elevation"], "Life income uses annuity math on death benefits."],
    ["Policy illustrations are meant to show:", "Values under stated assumptions—not guarantees of all numbers", ["Guaranteed stock returns", "Tomorrow's exam questions", "TDI fines"], "Illustrations are assumption tools."],
    ["Backdating (where permitted) is often used to:", "Save age and related premium within limits", ["Avoid free-look forever", "Create illegal rebates", "Skip underwriting always"], "Limited backdating can preserve issue age."],
    ["A facility of payment clause may allow:", "Limited payment for final expenses if no beneficiary is quickly found", ["Unlimited double indemnity always", "Agent commission advances", "Skipping incontestability"], "Facility of payment helps settle small last expenses."],
    ["Automatic premium loan (APL) may:", "Borrow from cash value to pay a missed premium and prevent lapse", ["Increase face amount free", "Cancel beneficiaries", "Create Medicare"], "APL prevents lapse using cash value."],
    ["Interest on policy loans is generally:", "Charged under contract terms and can increase the loan balance", ["Illegal everywhere", "Paid by TDI", "Equal to face amount"], "Unpaid loan interest grows the balance."],
    ["1035 exchanges allow:", "Tax-deferred exchange between eligible life/annuity contracts under IRS rules", ["Auto policy swaps", "CE trading", "Title transfers"], "1035 preserves deferral between eligible contracts."],
    ["COLA riders may:", "Increase benefits with inflation per rider terms", ["Eliminate underwriting", "Pay groceries weekly", "Set CE hours"], "COLA-style riders adjust for inflation."],
    ["Child term riders typically cover:", "Eligible children under the parent policy for a modest amount", ["The family home", "Long-term care only", "College tuition always tax-free"], "Child riders add small term on children."],
    ["Spouse term riders add:", "Temporary coverage on a spouse under the base policy", ["Auto liability", "HMO networks", "Free-look removal"], "Spouse riders add temporary protection."],
    ["Equity-indexed life may credit interest based on:", "An external index with caps/floors/participation rates", ["Unlimited stock picking by insured", "Flood maps", "DMV records"], "Indexed life links credits to indices within limits."],
    ["Variable universal life combines:", "UL flexibility with separate-account investment options", ["Only fixed guarantees", "Auto collision", "Medigap Plan G"], "VUL blends flexibility and market risk."],
    ["Buy-sell life funding supports:", "Transfer of business ownership at an owner's death", ["Weekly payroll only", "Office snacks", "Twitter ads"], "Buy-sell policies fund ownership buyouts."],
    ["Split-dollar arrangements share:", "Premium and/or benefits between employer and employee per agreement", ["Auto deductibles only", "CE hours", "Medicare cards"], "Split-dollar allocates policy costs/benefits."],
    ["Industrial/home service life historically featured:", "Small face amounts with frequent premium collection", ["Only mega COLI", "No beneficiaries", "Immediate annuities only"], "Industrial designs targeted small policies."],
    ["Endowment life pays the face amount:", "At a stated date or earlier death", ["Only after age 120", "Never", "Only for AD&D"], "Endowments mature at endowment date or death."],
    ["Return of premium term may:", "Refund premiums if the insured outlives the term per product rules", ["Guarantee equity gains", "Convert to auto", "Eliminate underwriting"], "ROP term returns premium on survival terms."],
    ["Family income policies historically combined:", "Permanent base with decreasing term for income after death", ["Only dental", "Only flood", "Only title"], "Family income blends permanent and decreasing term."],
    ["Jumping juvenile policies often:", "Increase face amount at adulthood without new evidence", ["Drop to zero at age 10", "Cover only auto", "Require monthly exams"], "Juvenile forms jump face at set ages."],
    ["Payor benefit on juvenile policies may waive premiums if:", "The payor dies or becomes disabled as defined", ["The child fails CE", "Flood occurs", "STOLI is created"], "Payor benefits protect juvenile coverage."],
    ["STOLI concerns focus on:", "Investor-initiated policies lacking legitimate insurable interest", ["Honest family protection", "Group employee coverage", "Credit life on car loans"], "STOLI is wagering disguised as insurance."],
    ["Viatical settlements historically involved:", "Terminally ill insureds selling policies for cash", ["Pet insurance", "Renters only", "Flood maps"], "Viaticals address terminal situations."],
    ["Standard nonforfeiture laws protect:", "Cash-value policy owner equity when premiums stop", ["Auto PIP minimums", "Food stamps", "Airline tickets"], "Nonforfeiture frameworks protect policy equity."],
    ["Graded premium whole life features:", "Lower early premiums that step up later", ["Highest premium day one always", "No death benefit", "Only AD&D"], "Graded premium eases early affordability."],
    ["Limited-pay whole life means:", "Premiums paid for a limited period then coverage continues", ["Premiums never stop", "Coverage ends when premiums stop always", "Only term renewals"], "Limited-pay concentrates premium years."],
    ["Single-premium life is funded by:", "One large upfront premium", ["100 annual payments", "No death benefit", "Identical to ART"], "Single-premium is front-loaded permanent coverage."],
    ["A spendthrift clause in a life policy generally:", "Restricts creditors from attaching proceeds payable to a beneficiary", ["Eliminates all death benefits", "Converts term to auto", "Waives CE forever"], "Spendthrift clauses protect beneficiary proceeds from some creditor claims."],
    ["The automatic premium loan option may:", "Pay overdue premiums from cash value to prevent lapse", ["Double the face amount", "Remove beneficiaries", "Skip underwriting forever"], "APL uses cash value to keep coverage in force when premiums are missed."],
    ["A reversionary beneficiary designation means:", "Proceeds revert to the owner if the beneficiary dies first", ["The insurer keeps all proceeds", "Only annuities qualify", "CE is waived"], "Reversionary designations return proceeds to the owner if the beneficiary predeceases."],
    ["Term conversion without evidence of insurability is limited by:", "Contract age limits and policy face amount caps", ["Unlimited amounts at any age", "Only flood policies", "DMV points"], "Conversion rights have contractual ceilings and age windows."],
    ["The payor clause on a juvenile policy identifies:", "Who is responsible for paying premiums", ["Which hospital is in-network", "The flood zone", "The auto VIN"], "Payor clauses name who funds the contract."],
    ["A life insurance illustration must:", "Distinguish guaranteed from non-guaranteed elements", ["Promise stock market returns", "Replace the policy contract", "Guarantee license renewal"], "Illustrations show assumptions; guarantees follow the contract."],
    ["The grace period in life insurance typically:", "Keeps coverage briefly active after a missed premium", ["Voids the policy immediately", "Doubles the death benefit", "Eliminates the beneficiary"], "Grace periods prevent accidental lapse for a short period."],
    ["A preferred risk classification usually receives:", "Lower premium than standard for the same coverage", ["No death benefit", "Automatic license appointment", "Free auto collision"], "Preferred classes reflect better underwriting risk."],
    ["The primary purpose of a life insurance needs analysis is to:", "Match coverage to financial obligations and goals", ["Maximize agent commission", "Avoid all underwriting", "Replace Medicare"], "Needs analysis sizes coverage to real obligations."],
    ["A policy's contestable period relates most closely to:", "Insurer ability to challenge material misrepresentation early on", ["Free-look cancellation", "Annual CE reporting", "Auto liability minimums"], "Contestability governs early insurer challenges to the contract."],
    ["Group term conversion rights often allow:", "Converting to individual permanent coverage without new medical evidence within limits", ["Unlimited cash withdrawals tax-free", "Skipping appointments forever", "Avoiding all premiums"], "Group conversion preserves insurability when employment ends."],
    ["The death benefit in a decreasing term policy typically:", "Declines over time while the premium may stay level", ["Increases every year automatically", "Equals Medicare Part B", "Is only for annuities"], "Decreasing term matches shrinking obligations like mortgages."],
    ["A life insurance policy's beneficiary designation should be:", "Reviewed after major life events like marriage or divorce", ["Set once and never changed", "Filed only with the DMV", "Ignored after issue"], "Life changes should trigger beneficiary reviews."],
    ["The purpose of a premium mode factor is to:", "Adjust total annual cost for monthly or quarterly payment schedules", ["Set flood zone rates", "Calculate auto ACV", "Replace underwriting"], "Modal factors reflect billing frequency costs."],
  ],
  health: [
    ["Coinsurance in major medical means:", "Sharing a percentage of covered costs after the deductible", ["Insurer pays nothing", "Fixed weekly disability only", "Auto gap"], "Coinsurance splits costs post-deductible."],
    ["A deductible is:", "Amount the insured pays before benefits begin for covered services", ["Maximum death benefit", "Agent commission", "License fee"], "Deductibles are upfront cost sharing."],
    ["An elimination period in DI is:", "A waiting period before disability benefits start", ["Mandatory hospital stay forever", "Free-look for life", "CE delay"], "Elimination periods delay DI benefits."],
    ["HMOs emphasize:", "Network care and sometimes PCP gatekeepers", ["Any provider worldwide at 100%", "Pure term life", "Unlimited OON free"], "HMOs manage care through networks."],
    ["PPOs generally allow:", "In-network discounts with some costlier out-of-network access", ["No networks", "Only Medicare Advantage naming", "Only workers comp"], "PPOs balance networks and choice."],
    ["COB exists to:", "Prevent duplicate payment when two plans cover the same expense", ["Increase commissions", "Force Medicare primary for kids always", "Eliminate deductibles"], "COB orders plan payments."],
    ["AD&D covers:", "Accidental death or listed dismemberment as defined", ["Any illness death", "Dental cleanings", "Maternity only"], "AD&D is accident-focused."],
    ["LTC insurance helps pay for:", "Custodial/ADL assistance in care settings", ["Only ER trauma for teens", "Stock losses", "Auto collision"], "LTC targets custodial needs."],
    ["Out-of-pocket maximum caps:", "Insured cost sharing on covered services in a period", ["Insurer claim payments", "Coverage after one visit", "Unlimited coinsurance forever"], "OOP maxes limit exposure."],
    ["Major medical uses:", "High limits with deductible and coinsurance sharing", ["Only hospital cash with zero OOP", "Cash value growth", "Dental only"], "Major medical handles large bills."],
    ["Group eligibility waits are:", "Probationary periods before new members qualify", ["Claim appeal waits", "Free-look days", "Exam delays"], "Employers often delay eligibility."],
    ["Hospital indemnity pays:", "Fixed cash per day/stay, not full bill reimbursement", ["100% of all bills always", "Only outpatient", "Life cash value"], "Indemnity pays stated cash."],
    ["Critical illness pays:", "Lump sum upon diagnosis of listed conditions", ["Weekly DI forever undefined", "Auto liability", "Flood"], "CI is lump-sum illness coverage."],
    ["BOE disability covers:", "Specified business overhead if owner is disabled", ["Personal mortgage only", "Vacations", "Illegal workers comp replacement"], "BOE covers overhead during disability."],
    ["Own-occupation DI is generally:", "More favorable than any-occupation definitions", ["Harder than any-occ", "Illegal everywhere", "Identical to AD&D"], "Own-occ focuses on one's occupation."],
    ["Any-occupation DI requires:", "Inability to perform any occupation reasonably fitted for", ["Inability to do hobbies only", "Permanent hospitalization", "Medicare entitlement"], "Any-occ is stricter."],
    ["Presumptive disability may pay:", "Full benefits for listed severe losses without ongoing income proof", ["Only after age 90", "Life benefits", "Ignore definitions"], "Presumptive lists trigger full benefits."],
    ["Guaranteed renewable health means:", "Insurer must renew but may raise class rates", ["Rates never change ever", "Only one claim", "Benefits zero monthly"], "Guaranteed renewable protects renewal."],
    ["Noncancelable DI means:", "Cannot cancel and premiums cannot rise while paid", ["Annual hikes freely", "Always group-only", "Ignore definitions"], "Noncan locks premium and renewal."],
    ["Medicare Part A relates to:", "Hospital inpatient coverage", ["Dental only", "Life cash values", "Auto PIP"], "Part A is hospital insurance."],
    ["Medicare Part B relates to:", "Physician/outpatient medical services", ["Skilled nursing forever unlimited", "Term life", "P&C warranties"], "Part B is medical insurance."],
    ["Medicare Part C is:", "Medicare Advantage through private plans", ["Life rider", "Workers comp exclusive", "Flood"], "Part C is private Medicare plans."],
    ["Medicare Part D is:", "Prescription drug coverage", ["AD&D only", "Title insurance", "Aviation hull"], "Part D covers prescriptions."],
    ["Medigap helps:", "Pay certain Medicare cost-sharing gaps", ["Replace Medicaid", "Provide cash value", "Insure boats"], "Medigap supplements Original Medicare."],
    ["Utilization review evaluates:", "Medical necessity and appropriativeness", ["Agent production", "CE quality", "SEO"], "UR manages care appropriateness."],
    ["Prior authorization is:", "Prospective approval before certain services", ["Life claim prepayment", "P&C rate setting", "License printing"], "Prior auth is prospective UR."],
    ["Concurrent review occurs:", "During a hospital stay", ["Only after death", "Only at issue", "Only for CE"], "Concurrent UR is mid-stay."],
    ["Retrospective review audits:", "Services after they occur", ["Only future schedules", "Only illustrations", "Only MIB"], "Retrospective UR is after-the-fact."],
    ["HSAs pair with:", "Qualifying high-deductible health plans", ["Whole life only", "Medicare Advantage always", "Credit life"], "HSAs accompany HDHPs."],
    ["FSAs allow:", "Pre-tax contributions for eligible expenses with historical use-it-or-lose-it rules", ["Life cash value", "AD&D only", "LTC replacement"], "FSAs are employer medical accounts."],
    ["COBRA relates to:", "Temporary continuation of group health after qualifying events", ["Life settlements", "Auto minimums", "NFIP flood"], "COBRA continues group eligibility temporarily."],
    ["HIPAA influenced:", "Health privacy and portability themes", ["CDL tests", "Aircraft hull", "Yacht liability"], "HIPAA is privacy/portability."],
    ["Mental health parity addresses:", "Comparable mental and medical benefits under laws", ["Eliminating therapy", "Life cash values", "Flood zones"], "Parity seeks comparable MH benefits."],
    ["Custodial care is:", "ADL help without continuous skilled nursing", ["Open-heart surgery", "ER trauma only", "Title insurance"], "Custodial care is non-skilled assistance."],
    ["ADLs include:", "Bathing, dressing, eating, toileting, transferring, continence", ["Tax filing", "Uber driving", "Options trading"], "ADL counts trigger LTC benefits."],
    ["Skilled nursing requires:", "Daily skilled care often after qualifying hospitalization", ["No hospitalization ever in every plan", "Only custodial help", "Life underwriting"], "SNF needs skilled care criteria."],
    ["Preventive care often has:", "Reduced cost sharing under modern plans", ["Zero coverage always", "Equals LTC custodial", "AD&D only"], "Prevention is emphasized today."],
    ["Prescription tiers sort by:", "Generic, preferred brand, non-preferred, specialty", ["Agent names", "VIN", "NAIC only"], "Formulary tiers drive RX sharing."],
    ["Specialty drugs involve:", "High-cost complex therapies with tighter management", ["Only OTC aspirin", "Life dividends", "Auto PD"], "Specialty pharmacy manages complex meds."],
    ["DME coverage may include:", "Wheelchairs and oxygen under medical necessity", ["Sports cars", "Jewelry", "Crypto"], "DME is reusable medical equipment."],
    ["Home health covers:", "Skilled services at home under criteria", ["Unlimited maid service", "Mortgage life", "Boat liability"], "Home health is skilled care at home."],
    ["Hospice focuses on:", "Palliative terminal care rather than curative treatment", ["Cosmetic surgery", "Variable life accounts", "Collision deductibles"], "Hospice is comfort-focused care."],
    ["POS plans combine:", "HMO-like features with some PPO-style OON options", ["Only term life", "Only title", "Only flood"], "POS blends managed care models."],
    ["EPO plans typically:", "Require network use except emergencies", ["Pay all providers 100% worldwide", "Are life settlements", "Are Medigap F only"], "EPOs are exclusive provider orgs."],
    ["Capitation means:", "Providers paid set amount per member regardless of visits", ["Unlimited fee-for-service always", "Life face amounts", "Agents set necessity"], "Capitation shifts utilization risk to providers."],
    ["Experience rating uses:", "Group's own claim history for premiums", ["Only community averages always", "VIN history", "Social likes"], "Experience rating reflects group claims."],
    ["ASO arrangements have employers:", "Self-fund claims with TPA administration", ["Fully insured with no employer risk", "Term life only", "Auto liability"], "ASO is self-funded group medical."],
    ["Stop-loss for self-funded employers protects against:", "Catastrophic claim volatility above attachment points", ["All eyeglasses forever", "Agent E&O only", "Title defects"], "Stop-loss caps self-funding downside."],
    ["Conversion after group termination may allow:", "Individual policy without evidence within limits/deadlines", ["Unlimited free major medical forever", "Automatic life settlements", "Skipping premiums forever"], "Conversion preserves continuity."],
    ["Recurrent disability provisions may:", "Treat related relapse as continuation for elimination period purposes", ["Create new life insurance", "Pay homeowners", "End AD&D"], "Recurrent disability avoids restarting elimination."],
    ["Relation of earnings clauses limit DI so:", "Total coverage does not exceed earned income inappropriately", ["Face amount of life rises", "P&C ACV sets", "Print IDs"], "These clauses police overinsurance."],
    ["Partial disability often means:", "Reduced capacity below total disability as defined", ["Full own-occ total", "Death", "ICU only"], "Partial is less than total under wording."],
    ["Key person DI helps a business when:", "A key employee is disabled", ["Term life auto-buys", "Workers comp illegally avoided", "FMLA skipped"], "Key person DI protects firm cash flow."],
    ["Disability buy-sell funds:", "Buyout of disabled partner interest", ["Lunches", "Plants", "CE courses"], "Buy-sell DI supports ownership transfer."],
    ["Blanket student accident covers:", "Students under school master policy for accident medical", ["Teachers life only", "Endowments", "Parking tickets"], "Blanket accident covers defined populations."],
    ["Travel accident provides:", "Trip-limited accident benefits", ["Permanent whole life", "Workers comp exclusive", "HO Section I"], "Travel products are trip-limited."],
    ["Specified disease policies pay for:", "Listed diseases under form design", ["Any cough", "Auto liability", "Pet boarding"], "Specified disease lists covered illnesses."],
    ["Comprehensive major medical combines:", "Broad benefits with deductible and coinsurance", ["Term only", "Hospital cash only", "Auto UM"], "Comprehensive major medical is broad coverage."],
    ["Family deductible may:", "Aggregate household deductible rules", ["Eliminate premiums", "Create life cash value", "Set license fees"], "Family rules aggregate cost sharing."],
    ["Urgent care is for:", "Non-life-threatening prompt needs", ["Cosmetic only", "Hospice only", "Title closing"], "Urgent care bridges office and ER."],
    ["Emergency provisions often:", "Cover sudden serious conditions with special sharing rules", ["Exclude all ER", "Pay life benefits", "Set CE"], "ER rules address urgent care."],
    ["Well-child visits are:", "Preventive pediatric checkups", ["CI lump sums", "Key person DI", "Title searches"], "Well-child is pediatric prevention."],
    ["Maternity in group plans often covers:", "Prenatal, delivery, postnatal subject to terms", ["Banned forever", "AD&D only", "Fathers life only"], "Maternity is common group category."],
    ["Substance use benefits are often:", "Included with behavioral health under rules", ["Identical to AD&D", "Agents only", "Medigap A only"], "SUD is behavioral health."],
    ["Mail-order RX may encourage:", "90-day maintenance supplies at lower sharing", ["Ban generics", "Replace surgeons", "Create STOLI"], "Mail order supports chronic adherence."],
    ["Second surgical opinion provisions encourage:", "Confirming elective surgery need", ["Skipping care", "Buying term", "Changing agents"], "Second opinions reduce unnecessary surgery."],
    ["Corridor deductibles historically linked:", "Basic and major medical layers", ["Term life only", "Annuities only", "Flood"], "Corridor deductibles stacked coverages."],
    ["Limited risk policies cover:", "Specified narrow situations", ["All medical worldwide unlimited", "Cash value life", "P&C packages"], "Limited risk forms are narrow."],
    ["Primary care includes:", "Routine general clinician visits", ["Only open-heart", "Experimental always covered", "Underwriting labs only"], "Primary care is first-contact medicine."],
  ],
  annuity: [
    ["An annuity primarily provides:", "Income over time, often for retirement", ["Home fire insurance", "Auto liability", "Workers comp"], "Annuities emphasize income distribution."],
    ["Accumulation period is when:", "Values build before payouts", ["Only death benefits pay weekly", "Already annuitized forever", "Medicare applies"], "Accumulation builds value pre-payout."],
    ["Annuitization converts:", "Contract value into an income stream under chosen option", ["Premiums into CE hours", "Life into auto", "Flood into life"], "Annuitization starts income."],
    ["SPIA is funded by:", "Single lump-sum premium", ["Unlimited payroll forever", "Only HSAs", "Title premiums"], "SPIAs start with one deposit."],
    ["Deferred annuities postpone income until:", "A future date while accumulating", ["Next week always", "Only after death", "Never"], "Deferred designs delay income."],
    ["Fixed annuities credit:", "Insurer-backed declared/guaranteed interest", ["Unlimited S&P with no caps", "Flood credits", "Agent residuals"], "Fixed annuities use general account support."],
    ["Variable annuities invest in:", "Separate account subaccounts with market risk", ["FDIC dollar-for-dollar always", "Home roofs", "Auto glass"], "Variable owners bear investment risk."],
    ["Indexed annuities link credits to:", "External index with caps/floors/participation", ["Unlimited day trading", "TDI scores", "VIN checks"], "Indexed formulas use index mechanics."],
    ["Surrender charges penalize:", "Early withdrawals for set years", ["Owners for staying", "Medicare", "Free-look forever"], "Surrender schedules discourage early exit."],
    ["Free withdrawal corridors may allow:", "Limited annual withdrawals without surrender charge", ["Unlimited full surrender daily", "Only life settlements", "Only CE"], "Free corridors reduce liquidity friction."],
    ["Life-only payout maximizes income but:", "Ends at annuitant death with no refund", ["Pays heirs forever regardless", "Only 30 days", "Pays auto claims"], "Life-only trades refund for income."],
    ["Period certain with life guarantees:", "At least a stated period even if early death", ["Only certain period no life", "Unlimited liquidity", "Medicare Advantage"], "Period certain protects early death."],
    ["Joint and survivor continues while:", "Either of two measuring lives survives", ["Only until first death always", "One hospital day", "Pets insured"], "J&S protects couples."],
    ["Refund options aim to:", "Return at least premium if death occurs early in payout", ["Double life faces", "Pay flood", "Waive CE"], "Refund features protect principal."],
    ["Tax deferral inside annuities means:", "Growth not taxed until distribution subject to rules", ["All withdrawals tax-free forever", "Premiums are Part A", "Gains taxed as wages always monthly"], "Deferral is not exemption forever."],
    ["Early withdrawal penalties often apply before:", "Age 59½ with exceptions", ["Age 18 always", "Age 100 only", "Age 12"], "Pre-59½ penalties often attach."],
    ["Exclusion ratio relates to:", "Taxable vs basis portion of each payment", ["Auto splits", "Flood elevation", "CE math"], "Exclusion ratio splits payment taxation."],
    ["Qualified annuities sit in:", "Retirement plan/IRA tax wrappers", ["Always tax-free forever", "Only P&C", "Only term"], "Qualified uses retirement tax rules."],
    ["Nonqualified annuities use:", "After-tax dollars outside retirement plans", ["Only 401(k) deferrals always", "Only Medicaid", "Only flood"], "Nonqualified uses after-tax premiums."],
    ["MVA features may:", "Adjust surrender values when rates move", ["Eliminate all risk", "Create STOLI", "Set auto premiums"], "MVAs respond to interest rate changes."],
    ["Bonus annuities may credit extra premium with:", "Often longer surrender schedules attached", ["Unlimited liquidity no tradeoffs", "Auto PIP", "Title insurance"], "Bonuses trade liquidity for credits."],
    ["Bailout provisions may allow:", "Surrender without charge if credited rates fall below threshold", ["Unlimited tax-free cash", "Skip underwriting", "CE waivers"], "Bailouts protect against rate drops."],
    ["Annuitization is generally irrevocable because:", "Principal is exchanged for income stream under contract", ["TDI bans all changes", "Owners never control", "IRS bans settlements"], "Annuitization locks income option."],
    ["Longevity annuities focus on:", "Income starting at advanced ages", ["Pay next week", "Collision", "Hospital indemnity only"], "Longevity products hedge living too long."],
    ["QLACs are:", "Qualified longevity annuity contracts in retirement accounts", ["Auto warranties", "NFIP", "Dental schedules"], "QLACs are longevity tools in qualified plans."],
    ["Separate accounts generally:", "Insulate variable assets differently than general account", ["Identical to HO Section I", "Held by TDI", "FDIC insured always"], "Separate accounts support variable investing."],
    ["Indexed caps:", "Limit maximum index-linked credit", ["Guarantee unlimited upside", "Apply only to term", "Set CE"], "Caps truncate upside."],
    ["Participation rates scale:", "Percent of index gain used in formula", ["Agent commission only", "Medicare premiums", "Flood zones"], "Participation scales index gains."],
    ["Spreads/margins may:", "Subtract from index gains before crediting", ["Add free unlimited interest", "Pay AD&D", "Create settlements"], "Spreads reduce credited interest."],
    ["Fixed account inside VA offers:", "More stable declared-interest allocation", ["Only crypto", "Only flood", "Only Medigap"], "Fixed accounts sit beside subaccounts."],
    ["Deferred annuity death benefits often:", "Pay at least a defined amount if owner/annuitant dies pre-annuitization", ["Never pay anyone", "Only pay agents", "Only Medicare"], "Many deferred contracts include DB features."],
    ["Suitability for annuities emphasizes:", "Matching liquidity horizon and needs", ["Max surrender always", "Ignoring age", "Skipping disclosures"], "Suitability protects buyers."],
    ["Annuity replacement requires:", "Honest comparison—not harmful churn", ["Hiding surrender", "Never disclosing fees", "Automatic twisting"], "Replacements need fair comparison."],
    ["Free-look on annuities allows:", "Short cancellation for refund under state rules", ["Cancel 20 years later free", "Skip taxes forever", "CE credit"], "Free-look mirrors consumer rights."],
    ["Two-tiered annuities historically favored:", "Higher values if annuitized vs cash surrender", ["Unlimited liquidity highest credits", "Auto coverage", "Title"], "Two-tier designs incentivize annuitization."],
    ["Group annuities fund:", "Retirement payouts under master contracts", ["One pet", "One auto", "Flood only"], "Group annuities support pensions."],
    ["Structured settlements use annuities to:", "Pay lawsuit awards over time", ["Insure sports cars", "Medigap G only", "Pay CE"], "Structured settlements pay over time."],
    ["Indexed floors often guarantee:", "Minimum credit such as 0% so index losses may not reduce account directly", ["20% gains always", "Remove surrender always", "Unlimited free look"], "Floors protect against negative index periods."],
    ["GMDBs protect:", "Minimum death benefit despite account declines", ["Agent renewals", "Medicare", "Flood"], "GMDBs are VA death benefit riders."],
    ["GLWBs allow:", "Lifetime withdrawals even if account depletes under rider rules", ["20-year free look", "Skip fees", "Avoid suitability"], "GLWBs create withdrawal guarantees."],
    ["GMIBs relate to:", "Guaranteed income base at annuitization under rider", ["Auto repairs", "Flood elevation", "CE passes"], "GMIBs protect annuitization floors."],
    ["GMABs aim to:", "Protect accumulation to minimum at future date", ["100% stock capture no fees", "Homeowners claims", "Issue licenses"], "GMABs are accumulation guarantees."],
    ["Annuitization vs systematic withdrawals differ because:", "Annuitization is generally irreversible; withdrawals keep account control", ["Identical always", "Both auto insurance", "Both require weekly TDI exams"], "Liquidity/control differs sharply."],
    ["1035 exchanges can move:", "Eligible annuity/life contracts tax-deferred under IRS rules", ["Auto for flood", "CE certificates", "Titles"], "1035 preserves deferral between eligible contracts."],
    ["Spousal continuation may let spouse:", "Continue contract tax-deferred under rules", ["Force taxable surrender always", "Convert to term", "Create STOLI"], "Spousal continuation preserves deferral."],
    ["Churning annuities is:", "Replacement mainly for commissions harming consumer", ["Honest needs sales", "Required free-look", "Mandatory CE"], "Churning is abusive replacement."],
    ["Liquidity needs matter because:", "Surrender charges and tax penalties can trap cash", ["Annuities always unlimited liquidity", "TDI bans surrenders", "Annuities are auto"], "Match liquidity to design."],
    ["Inflation risk for fixed payouts means:", "Fixed payments may lose purchasing power", ["Payments always track CPI with no riders ever", "Flood only", "Title only"], "Fixed income erodes in real terms."],
    ["Credit risk for fixed annuities means:", "Promises depend on insurer claims-paying ability", ["FDIC covers all always", "TDI personally guarantees every contract", "No insurer risk"], "Fixed promises are insurer obligations."],
    ["Market risk in VA means:", "Subaccount values can fall", ["Never change", "Only flood drives values", "Only CE scores"], "Variable owners bear volatility."],
    ["MYGAs typically credit:", "Guaranteed rate for multi-year term", ["Daily crypto floats", "Medigap plans", "HO-3 forms"], "MYGAs resemble CD-like terms."],
    ["Rate lock windows on new premiums may:", "Hold declared rate for funds received within period", ["Guarantee stock options", "Set auto premiums", "Issue licenses"], "Rate windows matter for fixed deposits."],
    ["Charitable gift annuities:", "Blend donor income with charitable gift under philanthropy rules", ["Illegal STOLI", "Flood policies", "CDL endorsements"], "CGAs combine giving with income."],
    ["Temporary life annuities pay:", "For life or period, whichever is shorter", ["Forever regardless", "Only weekends", "Only after 120"], "Temporary life is life contingent with max period."],
    ["Cash refund vs installment refund differ by:", "Lump sum vs continued installments of unpaid premium", ["Whether cars covered", "CE hours", "Medicare parts"], "Refund mechanics vary."],
    ["AIR in variable payouts affects:", "Whether payments rise/fall vs assumed rate", ["Only term premiums", "Only title rates", "Only flood"], "AIR benchmarks variable payment changes."],
    ["General account backs:", "Fixed annuity guarantees and many non-variable promises", ["Only separate-account stocks no insurer risk", "Only agent errors", "Only titles"], "General account supports fixed promises."],
    ["VA prospectuses disclose:", "Fees, risks, and subaccount details for securities sales", ["Replace all state laws", "Are optional ads only", "Set CE hours"], "Variable annuities are securities hybrids."],
    ["M&E charges compensate insurer for:", "Guarantees and expenses inside VA", ["Illegal always", "Pearson fees", "Flood premiums"], "M&E is common VA fee layer."],
    ["Contingent deferred annuities may:", "Wrap longevity protection around portfolios", ["Insure boats only", "AD&D only", "Replace title"], "CDAs are longevity wrappers."],
    ["Suitability questionnaires gather:", "Assets, objectives, horizon, and tolerance", ["Favorite teams only", "Agent birthday", "Flood jokes"], "Fact-finders support suitability."],
    ["Tax on non-natural owners can:", "Accelerate annuity taxation for certain entities", ["Whether homes burn", "VIN validity", "Flood maps"], "Entity ownership affects taxation."],
    ["Income option tradeoffs include:", "Higher pure-life income vs refund protection", ["Whether TDI exists", "VIN validity", "Flood maps"], "Refund features lower income vs pure life."],
  ],
  ethics: [
    ["Twisting is:", "Misleading replacement to the client's disadvantage", ["Honest comparison", "Required free-look", "Paying CE"], "Twisting is deceptive replacement."],
    ["Rebating is:", "Improper inducements outside the filed contract when prohibited", ["Filed premium only", "Free-look delivery", "CE filing"], "Illegal rebating buys business improperly."],
    ["Misrepresentation includes:", "False statements about terms, benefits, or dividends", ["Accurate summaries", "Prospectuses for VA", "Policy delivery"], "Misrepresentation misstates products."],
    ["Defamation in insurance is:", "False malicious injury to another's business reputation", ["Honest public ratings data", "Filing claims", "Free-look notices"], "Defamation uses falsehoods against competitors."],
    ["Coercion removes:", "Free informed consumer choice through threats or pressure", ["Voluntary informed buying", "Approved illustrations", "Free-look windows"], "Coercion is improper pressure."],
    ["False advertising misleads about:", "Benefits, costs, or financial condition", ["Clear accurate marketing", "License numbers where required", "Filed rates"], "Ads must be truthful."],
    ["Fiduciary premium care requires:", "Honest handling and timely remittance", ["Personal vacation use of premiums", "Indefinite float for interest", "Never receipting"], "Premiums are trust funds."],
    ["Controlled business concerns arise when:", "License serves mainly producer's own interests", ["Serving many unrelated clients", "Completing CE", "Maintaining appointments"], "Licenses serve the public."],
    ["Suitability means recommending products that:", "Fit the customer's needs and circumstances", ["Maximize surrender always", "Ignore age/liquidity", "Hide fees"], "Suitability centers the consumer."],
    ["Churning harms clients by:", "Harmful replacements for commissions", ["Updating beneficiaries legitimately", "Delivering free-look", "Completing CE"], "Churning exploits clients."],
    ["Sliding adds coverages:", "Without informed consent", ["With clear optional rider explanation", "With delivery", "With CE"], "Sliding sneaks unwanted coverages."],
    ["Fraudulent applications submit:", "False material information", ["Truthful histories", "Honest beneficiaries", "Accurate ages"], "Application fraud undermines underwriting."],
    ["Coaching omitted medical history is:", "Unethical and potentially fraudulent", ["Required free-look", "Mandatory STOLI", "CE credit"], "Never coach lies on applications."],
    ["Privacy duties require:", "Protecting NPPI and sharing only as permitted", ["Selling SSNs", "Public medical files", "Ignoring privacy notices"], "Privacy is legal/ethical duty."],
    ["Fair claims require:", "Good-faith investigation and communication", ["Ignoring claims a year", "Blind denials", "Paying agents instead of insureds"], "Good-faith claims handling is mandatory."],
    ["Unfair discrimination includes:", "Refusing to insure on prohibited factors alone", ["Lawful underwriting factors", "Preferred risk lawfully", "Actuarial age rating where allowed"], "Unfair discrimination violates law."],
    ["Boycott/coercion in insurance may involve:", "Improper restraint of commerce", ["Normal competitive pricing", "Authorized appointments", "Lawful underwriting"], "Anticompetitive coercion is prohibited."],
    ["Unfair claim settlement example:", "Refusing to pay without reasonable investigation", ["Prompt fair investigation", "Clear denial reasons", "Timely updates"], "Stonewalling is unfair."],
    ["Commingling premiums is:", "Serious fiduciary violation", ["Best practice", "Required free-look", "CE homework"], "Keep trust funds segregated."],
    ["Disclosing policy limitations when asked is:", "Required for honest dealing", ["Optional if it hurts sale", "Banned by free-look", "Only for P&C"], "Disclose material limits."],
    ["Unlicensed solicitation is:", "Generally prohibited", ["Always fine if friendly", "Required STOLI", "Free-look right"], "Solicitation needs licensing."],
    ["Acting without appointment when required is:", "Improper/unlicensed activity risk", ["Always fine", "Encouraged by TDI", "CE substitute"], "Appointments authorize representation."],
    ["Failing to deliver policy undermines:", "Free-look and contract rights", ["Agent parking", "Flood maps", "Titles"], "Delivery starts examination rights."],
    ["False financial statements about insurers are:", "Unfair/deceptive", ["Good advertising", "Required illustrations", "CE credits"], "Don't lie about solvency."],
    ["High-pressure sales preventing informed choice are:", "Unethical and often unlawful", ["Best practice", "Required for annuities", "Part of free-look"], "Consumers need clarity and time."],
    ["Commission-only recommendations ignoring fit are:", "Suitability failures", ["Always correct", "Required by NAIC always", "Free-look compliance"], "Compensation cannot override fit."],
    ["Hiding surrender charges in replacement is:", "Material omission harming consent", ["Optional trivia", "Prohibited disclosure", "CE only"], "Replacement must surface costs."],
    ["Forging signatures is:", "Fraud", ["Delegable paperwork", "Free-look admin", "Underwriting help"], "Never forge signatures."],
    ["Promising uncontrollable claim outcomes is:", "Misrepresentation risk", ["Required closing", "Free-look language", "CE homework"], "Don't guarantee claim results."],
    ["Fear tactics without factual basis are:", "Coercive/misleading pressure", ["Suitable advice", "Required illustration", "Appointment paperwork"], "Scare tactics without basis are unethical."],
    ["Secure health data is:", "Ethical and often legal duty", ["Optional courtesy", "Banned practice", "Only for settlements"], "Guard medical privacy."],
    ["False claims are:", "Insurance fraud", ["Fair claims practice", "Free-look right", "CE activity"], "Fraudulent claims are crimes."],
    ["Inventing loss dates is:", "Fraud facilitation", ["Good service", "Required COB", "Medigap rule"], "Don't fabricate loss facts."],
    ["Late premium remittance can be:", "Fiduciary misconduct", ["Normal float always", "Free-look", "CE"], "Timely remittance required."],
    ["Sharing commissions with unlicensed solicitors may be:", "Unlawful sharing", ["Always required", "Medicare rule", "Flood elevation"], "Commission sharing is strict."],
    ["Honest replacement comparison supports:", "Ethical replacement", ["Twisting", "Churning", "Sliding"], "Transparent comparison is good practice."],
    ["Documenting recommendations helps prove:", "Suitability and understanding", ["Free-look never existed", "CE optional", "Appointments irrelevant"], "Files protect clients and producers."],
    ["Refusing to leave when asked is:", "Coercive pressure", ["Normal persistence", "Required suitability", "Free-look delivery"], "Respect client autonomy."],
    ["Selling in language client cannot understand without help is:", "Ethical problem for informed consent", ["Best practice", "Required STOLI", "CE credit"], "Ensure comprehension."],
    ["False competitor solvency rumors are:", "Defamation", ["Required competitive speech", "Free-look text", "Illustrations"], "Don't spread false competitor claims."],
    ["Bribes to place business are:", "Corrupt and unethical", ["Ordinary agency management", "Free-look admin", "Underwriting"], "Bribery has no place."],
    ["Using client policy values secretly for personal loans is:", "Theft/fiduciary breach", ["Standard APL", "Free-look", "CE"], "Client assets aren't personal capital."],
    ["Ignoring CE obligations risks:", "License discipline", ["Higher commissions automatically", "Automatic appointments", "Free licenses"], "CE keeps licenses active."],
    ["Missing affiliation in ads when required is:", "Transparency failure", ["Best SEO", "Free-look content", "MIB code"], "Identify who is advertising."],
    ["Unauthorized insurer sales can be:", "Illegal and harmful", ["Always fine", "Required experiment", "CE elective"], "Sell authorized insurers where required."],
    ["Missing replacement notices is:", "Compliance and ethics breach", ["Optional courtesy", "CE substitute", "Underwriting only"], "Replacement forms matter."],
    ["Overstating coverage to close is:", "Misrepresentation", ["Creative illustration", "Free-look", "Appointment form"], "Sell what contract provides."],
    ["Understating premiums while knowing fees apply is:", "Misleading", ["Required closing", "CE filing", "MIB"], "Disclose total cost drivers."],
    ["False urgency for seniors is:", "Abusive sales practice risk", ["Standard annuity law", "Free-look", "Flood rule"], "False urgency preys on vulnerable buyers."],
    ["Blank signed applications are:", "Dangerous/improper", ["Efficient underwriting", "Required free-look", "CE"], "Apps should be complete when signed."],
    ["Needs analysis before product selection supports:", "Ethical suitable sales", ["Twisting", "Churning", "Sliding"], "Needs before product."],
    ["Explaining free-look clearly is:", "Consumer-protective", ["Twisting", "Rebating", "Defamation"], "Free-look education helps buyers."],
    ["Fabricated testimonials are:", "False advertising", ["Required marketing", "Free-look", "CE"], "Don't invent endorsements."],
    ["Knowingly selling useless duplicate coverage is:", "Unsuitable/abusive", ["Always ideal", "Required COB", "Free-look"], "Don't stack useless insurance."],
    ["Coaching false income on DI apps is:", "Fraud coaching", ["Needs analysis", "Free-look help", "CE"], "Truthful underwriting data only."],
    ["Claiming TDI guarantees a product falsely is:", "Misrepresentation", ["Accurate advertising", "Required illustration", "MIB note"], "Don't invent regulator guarantees."],
    ["Personal premium kickbacks can be:", "Illegal rebating", ["Always required", "Free-look", "Appointment paperwork"], "Personal kickbacks can be rebates."],
    ["Honest error correction should be:", "Transparent with initials/new forms as required", ["Hidden alterations", "Forged fixes", "Ignored"], "Correct mistakes properly."],
    ["E&O awareness helps producers:", "Recognize liability from advice errors", ["Ignore ethics", "Skip CE", "Forge apps"], "E&O tracks ethics and competence."],
    ["When unsure on complex tax/legal questions, producers should:", "Refer to qualified professionals", ["Invent answers confidently", "Hide uncertainty", "Forge documents"], "Stay in lane; escalate properly."],
    ["Fair treatment of similarly situated clients supports:", "Ethical non-discrimination in service", ["Illegal discrimination", "Twisting", "Churning"], "Fair dealing is foundational."],
    ["Recording consent where required is:", "Compliance-minded", ["Always illegal", "Twisting", "Rebating"], "Follow consent/recording laws."],
    ["Selling variable products without proper licenses is:", "Unlawful", ["Always permitted everywhere", "Free-look compliance", "CE elective"], "Securities lines need credentials."],
    ["Outline of coverage where required aids:", "Informed consent", ["Twisting", "Sliding", "Defamation"], "Summaries help consumers compare."],
    ["Complaint response should include:", "Prompt honest investigation", ["Deleting files", "Ignoring client", "Threatening client"], "Complaints demand professionalism."],
    ["Quota over client fitness is:", "Ethics/suitability conflict", ["Best practice", "Required free-look", "CE goal"], "Clients before quotas."],
    ["Putting insurer quota above suitability fails:", "Ethical selling standards", ["Free-look only", "Flood rules", "Title norms"], "Suitability beats quotas."],
    ["Honest advertising of non-guaranteed elements is:", "Required ethical marketing", ["Twisting", "Rebating", "Defamation"], "Label non-guaranteed elements clearly."],
  ],
  "texas-law": [
    ["TDI primarily:", "Regulates insurers and producer licensing in Texas", ["Sets federal Medicare exclusively", "Issues driver licenses only", "Runs Pearson globally"], "TDI is Texas's insurance regulator."],
    ["Weak Texas law performance sinks many because:", "Exam mixes general and state-specific scored items", ["Only typing speed matters", "Only auto schedules", "Only flood certificates"], "Texas block matters on its own."],
    ["After passing exam you still need:", "Application, fingerprints, and appointments as applicable", ["Automatic nationwide appointments", "Skip all forms", "Avoid CE forever"], "Exam pass ≠ finished licensing."],
    ["Texas often noted for:", "No mandatory pre-licensing hours on many lines", ["400 classroom hours always", "Banning practice tests", "Eliminating ethics"], "Self-study is common."],
    ["CE for active licenses generally:", "Requires approved hours each renewal cycle", ["Never after first pass", "Instagram posts", "Auto mechanics only"], "CE keeps licenses current."],
    ["Appointments authorize:", "Representing a particular insurer's products", ["Overwriting TDI regulations", "Avoiding fingerprints forever", "Setting statewide rates"], "Appointments link producers to insurers."],
    ["Guaranty association purpose is:", "Limited protection if member insurer becomes insolvent", ["Guarantee commissions", "Replace underwriting", "Set CE providers"], "Guaranty is limited safety net—not sales pitch."],
    ["Using guaranty as sales inducement is:", "Improper/prohibited marketing", ["Required closing", "Free-look language", "MIB coding"], "Don't pitch guaranty funds to sell."],
    ["Replacement requires:", "Honest disclosures and comparison forms", ["Hiding cash values", "Skipping notices", "Automatic twisting"], "Replacement rules protect consumers."],
    ["Twisting under Texas themes means:", "Misleading replacement to client's detriment", ["Required free-look", "Honest suitability", "Paying CE"], "Twisting is deceptive replacement."],
    ["Prohibited rebating involves:", "Improper inducements outside filed contract", ["Charging filed premiums only", "Delivering policies", "Scheduling exams"], "Rebates outside contract can be illegal."],
    ["Application misrepresentation can lead to:", "Policy challenges and fraud consequences", ["Automatic double benefits", "Free CE", "Automatic appointments"], "Truthful apps are mandatory."],
    ["Unfair advertising includes:", "Misleading statements about benefits or financial condition", ["Clear accurate descriptions", "Required license disclosures", "Factual TDI references"], "Ads must not deceive."],
    ["Defamation as unfair practice includes:", "False malicious statements injuring another in insurance business", ["Sharing public ratings accurately", "Filing claims", "CE transcripts"], "Don't spread false competitor claims."],
    ["Fiduciary premium handling expects:", "Proper remittance—not personal use", ["Commingle with rent", "Hold indefinitely for interest", "Never receipt"], "Premium trust accounting is strict."],
    ["Controlled business restrictions ensure licenses:", "Serve the public not mainly producer interests", ["Only cover agent family forever", "Ignore CE", "Skip appointments"], "Licenses are for public service."],
    ["Fair claims practices require:", "Good-faith investigation and timely communication", ["Ignore claims", "Deny without review", "Pay whoever asks without investigation"], "Claims conduct is regulated."],
    ["Selling without required license may face:", "Disciplinary and legal consequences", ["Automatic CE credit", "Higher legal commissions", "TDI congratulations"], "Licensing is mandatory."],
    ["License renewal depends on:", "CE and administrative renewal requirements", ["Never studying again", "TikTok posts", "Owning a car"], "Renewal is administrative + CE."],
    ["Exam outlines help:", "Plan study by topic weighting", ["List live questions verbatim", "Replace ethics", "Guarantee pass"], "Outlines guide study—not dumps."],
    ["Pearson VUE in Texas:", "Administers licensing exams under contract", ["Issues appointments automatically", "Sets TDI statutes", "Provides free CE forever"], "Pearson VUE is exam administrator."],
    ["After failing you may:", "Retest per current fee/scheduling rules", ["Never test again", "Auto license", "Skip fingerprints forever"], "Retesting is allowed."],
    ["Ethics items often reward:", "Honesty, disclosure, and client fitness answers", ["Hidden fees", "Twisting encouragement", "Hiding free-look"], "Pick consumer-protective choices."],
    ["Texas Insurance Code themes emphasize:", "Licensing conduct, honest marketing, consumer protection", ["Unlimited rebating", "Secret commissions only", "Ignoring appointments"], "State code sets conduct rails."],
    ["Commission sharing with unlicensed solicitors is typically:", "Restricted or prohibited", ["Always required", "Free-look rule", "Medicare Part A"], "Pay only properly licensed parties."],
    ["Replacement notices exist to:", "Help consumers compare fairly", ["Speed churning", "Hide cash values", "Skip free-look"], "Notices support informed replacement."],
    ["Temporary licenses (where available) allow:", "Limited practice under rules for short period", ["Replace all exams forever", "Eliminate CE forever", "Nationwide authority automatic"], "Temporary licenses are limited."],
    ["Nonresident licensing can allow:", "Texas authority under reciprocity-like rules with compliance", ["Skipping all laws", "Selling without home license ever", "Avoiding fingerprints always everywhere"], "Nonresident paths still require compliance."],
    ["Inactive licenses mean:", "You may not solicit until restored", ["Sell quietly", "CE never mattered", "Appointments continue forever"], "Don't solicit on dead license."],
    ["Reporting background on applications is:", "Part of license honesty", ["Optional trivia", "Only P&C boats", "CE elective"], "Disclose what forms ask."],
    ["Unapproved trade names improperly used may:", "Violate licensing/marketing rules", ["Improve SEO always", "Replace CE", "Create free-look"], "Soliciting names can be regulated."],
    ["Policy delivery starts rights such as:", "Free-look examination periods", ["Unlimited twisting", "Automatic rebates", "CE exemptions"], "Delivery timing matters."],
    ["Records retention expects:", "Keeping transaction records for required periods", ["Delete weekly", "Never document suitability", "Forge apps"], "Keep required files."],
    ["Responding to TDI inquiries should be:", "Timely and truthful", ["Ignored", "Delayed forever", "Answered with forged docs"], "Cooperate with regulator."],
    ["Unauthorized insurer sales can:", "Leave consumers unprotected and expose producer to penalties", ["Clever loophole", "Replace guaranty associations", "Satisfy CE"], "Only authorized insurers where required."],
    ["UTPA-style rules target:", "Deceptive, unfair, or abusive methods", ["Honest disclosures", "Accurate illustrations", "Lawful underwriting"], "UTPA polices market conduct."],
    ["Fake TDI endorsement in ads is:", "Misleading", ["Required", "Free-look text", "MIB"], "Don't fake regulator endorsements."],
    ["Blank signed applications are:", "Improper application practice", ["Efficient underwriting", "Required free-look", "CE"], "Complete accurate applications only."],
    ["Suitability documentation shows:", "Why recommendation fit client", ["Twisting fine", "Rebates mandatory", "CE optional"], "Document fit."],
    ["Privacy notices align with:", "Consumer protection expectations", ["Public SSN dumps", "Selling medical files", "Ignoring privacy rules"], "Protect NPPI."],
    ["License numbers on advertising promote:", "Transparency and accountability", ["Twisting", "Rebating", "Defamation"], "Identify who is marketing."],
    ["Missing appointments while selling carrier products risks:", "Unauthorized representation", ["Automatic CE credit", "Higher guaranty limits", "Free licenses"], "Stay appointed as required."],
    ["Exam security prohibits:", "Capturing or sharing live exam content", ["Using official outlines", "Free practice like this site", "Reading Insurance Code"], "Don't steal exam items."],
    ["Candidate agreements ban:", "Cheating and content disclosure", ["Sleeping after exam", "Buying CE later", "Applying for fingerprints"], "Honor exam integrity."],
    ["Free-look cancellation requests should be:", "Processed per rules", ["Refused to force keeping policy", "Secret penalty charged", "Forged new app"], "Honor free-look."],
    ["Illustrations not guarantees supports:", "Honest Texas marketing", ["Misrepresentation", "Twisting", "Defamation"], "Label non-guaranteed elements."],
    ["Replacement solely for commissions violates:", "Ethics and replacement suitability", ["Free-look only", "Flood elevation", "Title closing"], "Don't churn for pay."],
    ["Fingerprint/background steps exist to:", "Screen applicants for trustworthiness", ["Raise pass rates magically", "Replace CE", "Set auto rates"], "Background checks protect public."],
    ["Holding out as advisor may require:", "Careful compliance with licensing/disclosure rules", ["No credentials ever", "Only social bio", "Ignoring securities lines"], "Titles imply regulated advice."],
    ["NSF premium checks should be handled:", "Per insurer procedures—not hidden improperly", ["Ignored forever", "Forged new check", "Instant twisting replacement"], "Handle billing cleanly."],
    ["Outline of coverage documents help:", "Consumers understand benefits and limits", ["Hide exclusions", "Skip free-look", "Avoid appointments"], "Outlines aid comprehension."],
    ["Lines of authority matter because:", "Producer may sell only authorized lines", ["Unlimited global products automatic", "Only flood forever", "Only CE teaching"], "Know line limits."],
    ["Life & health authority covers:", "Life and health-related products under that line", ["Only homeowners Section I", "Only auto liability", "Only workers comp debates"], "L&H is distinct from P&C."],
    ["P&C authority covers:", "Property and liability lines rather than L&H", ["Only annuities", "Only Medigap", "Only STOLI"], "P&C is separate exam/path."],
    ["Referral fees without license may be:", "Restricted activity depending on conduct", ["Always fully compliant", "Automatically appointed", "Exempt from all laws"], "Referrals can require licenses."],
    ["Ethics CE hours exist because:", "Market conduct failures harm public", ["Ethics optional trivia", "TDI hates studying", "Pearson needs content"], "Ethics CE reinforces conduct."],
    ["Keep CE proof for:", "Renewals and audits", ["Office decoration only", "Flood maps", "VIN checks"], "Retain CE certificates."],
    ["If TDI suspends license, producer should:", "Stop regulated activity until reinstated", ["Keep selling quietly", "Increase churning", "Ignore appointments"], "Suspension means stop."],
    ["Update address when required supports:", "License file accuracy", ["Twisting", "Rebating", "Defamation"], "Update contact data."],
    ["Imaginary TDI deadlines to force sales are:", "Deceptive pressure", ["Required closing", "Free-look text", "CE"], "Don't invent regulatory urgency."],
    ["Quoting other states as Texas requirements can be:", "Misleading", ["Best practice", "Required", "Free-look"], "Know Texas-specific rules."],
    ["Telling candidates exam is easy so skip Texas law is:", "Bad advice given fail patterns", ["Accurate for everyone", "Required by Pearson", "CE credit"], "Texas law sinks many."],
    ["Strong Texas strategy includes:", "Heavy Texas law/ethics drill plus general knowledge", ["Only joke mnemonics", "Ignore consumer protection", "Only auto PD"], "Balance general + state."],
    ["Exam center misconduct should be:", "Reported per vendor rules", ["Ignored", "Used for free answers", "Livestreamed with live items"], "Follow test center conduct."],
    ["Unauthorized materials in exam room are:", "Cheating/violation", ["Recommended", "Required free-look practice", "CE"], "Follow check-in rules."],
    ["Discussing live exam items online after testing is:", "Often prohibited by candidate agreements", ["Required marketing", "Free CE", "TDI advertising"], "Don't disclose secure content."],
    ["Consumer-protective ethics answers usually choose:", "Disclosure, honesty, suitability over commission", ["Hidden fees and fear", "Twisting", "Rebating"], "Ethics keys reward integrity."],
    ["Terminated appointments mean producers must:", "Track active appointments before selling that carrier", ["Assume forever authority", "Skip TDI rules", "Ignore clients"], "Monitor appointment status."],
    ["Broker vs agent difference reflects:", "Representation and compensation structure under law", ["Whether CE exists", "Whether free-look exists", "Whether floods occur"], "Roles differ by representation."],
    ["Exam pass is not substitute for:", "Ongoing ethical conduct after licensing", ["All future CE automatically", "All appointments forever", "All fingerprinting forever always"], "Passing starts professional duty."],
    ["Guaranteed exam dump marketing is:", "Misleading scam risk", ["TDI publishes forms nightly", "Pearson emails answers", "Guaranty sells dumps"], "Avoid stolen-content scams."],
    ["Educational practice tests should be treated as:", "Original study tools—not live exam recreations", ["Official Pearson forms", "TDI regulations themselves", "Appointment paperwork"], "Practice ≠ live exam."],
    ["If client was misled by another agent, help with:", "Honest information and proper remedial options", ["Invent worse rumors", "Forge replacement", "Ignore free-look"], "Correct harm ethically."],
    ["When statute conflicts with marketing flyer, rely on:", "Law/contract—not flyer", ["Flyer always", "TikTok comments", "Guesswork"], "Legal documents control."],
    ["Secured client files align with:", "Texas consumer protection and privacy expectations", ["Public whiteboard histories", "Open SSN binders", "Unlocked cars with apps"], "Secure records."],
    ["Without appointment you generally should not:", "Solicit that carrier's products as their producer", ["Study brochures academically", "Take CE", "Read TDI sites"], "Appointment precedes representation."],
    ["Lapsed CE can block:", "Legal solicitation until cured", ["Grocery shopping", "Watching football", "Paying rent"], "Cure CE/license before selling."],
    ["License application honesty includes:", "Disclosing required background information", ["Omitting convictions asked about", "Inventing employers", "Fake CE certificates"], "Application honesty is foundational."],
    ["Borrowing another producer's license number in ads is:", "Fraudulent/improper", ["Creative branding", "Free-look compliance", "CE"], "Don't borrow credentials."],
    ["Pass guarantee implying insider exam access is:", "Misleading marketing risk", ["Required by TDI", "Pearson policy", "Guaranty rule"], "Don't imply stolen exam access."],
    ["Consumer complaints to TDI can trigger:", "Investigations and discipline", ["Automatic license upgrades", "Free CE forever", "Higher commissions"], "Complaints have teeth."],
    ["Good market conduct includes:", "Clear disclosures, fair claims, suitable recommendations", ["Twisting contests", "Rebate auctions", "Fear closings"], "Conduct quality is the brand."],
    ["Pre-exam study week should emphasize:", "Texas law drills, ethics verbs, timed mixed mocks", ["One brochure only", "Avoid Texas items", "Only flood questions"], "Match study to exam shape."],
    ["Exam scores as percentages mean:", "You need enough correct across general and Texas areas", ["One lucky guess passes", "Texas items don't count", "General don't count"], "Both domains matter."],
    ["Fake TDI certification in ads is:", "Likely misleading", ["Always accurate", "Required wording", "Free-look text"], "Don't fake certifications."],
    ["After client death, producer service includes:", "Helping beneficiaries start claim process properly", ["Hiding policy", "Changing beneficiaries secretly", "Refusing calls"], "Service ethics continues at death claims."],
    ["Dishonest claim loss dates are:", "Fraud", ["Helpful service", "Free-look right", "CE practice"], "Honest loss dates only."],
    ["Exam readiness is strongest when you can:", "Explain why consumer-protective choice wins on ethics", ["Memorize unrelated trivia only", "Ignore definitions", "Skip practice"], "Understanding beats rote."],
    ["Safest prep site marketing claim is:", "Original practice aligned to public outlines—not stolen live items", ["Tomorrow's exact Pearson form", "TDI wrote our questions", "Guaranty partners for dumps"], "Stay on lawful educational side."],
  ],
};

const FILES = {
  life: ["life.ts", "LIFE_QUESTIONS", "life"],
  health: ["health.ts", "HEALTH_QUESTIONS", "health"],
  annuity: ["annuity.ts", "ANNUITY_QUESTIONS", "ann"],
  ethics: ["ethics.ts", "ETHICS_QUESTIONS", "ethi"],
  "texas-law": ["texas-law.ts", "TEXAS_LAW_QUESTIONS", "txlaw"],
};

for (const [domain, [file, exportName, prefix]] of Object.entries(FILES)) {
  let existing = parseQuestions(file);
  const existingPrompts = new Set(existing.map((q) => q.prompt));
  const target = TARGETS[domain];
  let n = existing.length;

  // Top up only with unique supplemental prompts (no duplicate stems).
  for (const [prompt, correct, wrongs, explanation] of SUPPLEMENT[domain]) {
    if (existing.length >= target) break;
    if (existingPrompts.has(prompt)) continue;
    n += 1;
    existing.push(mc(domain, prefix, n, prompt, correct, wrongs, explanation));
    existingPrompts.add(prompt);
  }

  writeDomain(file, exportName, existing);
  console.log(domain, existing.length);
}

console.log(
  "Total L&H:",
  Object.keys(FILES).reduce((s, d) => s + parseQuestions(FILES[d][0]).length, 0),
);
